bin: git
silent: false
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/mnhkahn/cyeam-cli
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - docs
        - style
        - chore
        - test
        - ci
        - build
        - revert
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      docs: Documentation
      style: Styles
      chore: Miscellaneous Tasks
      test: Tests
      ci: CI/CD
      build: Build System
      revert: Reverts
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE